### ISSUE TITLE
Ghost Spawning and proper movement

### ISSUE THREAD

**Issue by Ahillman2000** [Ahillman2000/Untitled-VR-game#3]
**Describe the solution you'd like**
Manager to handle spawning ghosts (maybe a ghost manager to handle most ghost relative behavior's) and an improve movement system to that already implemented

**Describe alternatives you've considered**
Keep pre-existing movement system

**Comment by charlie2099** [comment]
The Ai Director should/will probably handle ghost spawning. Then depending on the haunt intensity it could spawn more or fewer ghosts, or just make the one ghost more dangerous over time until it eventually kills the player should the players fail to banish it.  

As for it's behaviour, each ghost should be responsible for it's own behaviour I think rather than an external force such as a manager dictating it. For e.g. The ShadowPerson can have it's own dedicated class with a state machine component, and each of it's behaviour states are encapsulated into their own individual classes. These can then be fed into it's state machine and any common behaviour states across ghost types can be reused by just plugging them into said ghost's state machine. 

It's behaviours don't need to be anything complex, and I have a state machine setup and ready to go so this is feasible for the alpha.
